Updated virt-* local scripts

diff --git a/bin/virt-addr b/bin/virt-addr
--- a/bin/virt-addr
+++ b/bin/virt-addr
@@ -1,8 +1,19 @@
 #!/bin/sh
 
-# Get the MAC address of vnet0
+# Get the MAC address of the first interface.
 mac=$(virsh domiflist $1 | grep vnet0 | awk '{print $5}')
+
+if [[ "$mac" = "" ]]
+then
+	echo "$1 not found. Has domain has not been created?"
+	exit 1
+fi
 
 # Get the ip address assigned to this MAC from dnsmasq
 ip=$(awk -vmac=$mac '$2 == mac {print $3}' /var/lib/libvirt/dnsmasq/default.leases )
+
+if [[ "$ip" = "" ]]
+then
+	echo "No IP for $1 found. Does it have a network configured?"
+	exit 1
 echo $ip
